-- MySQL schema for KarmaKind
CREATE DATABASE IF NOT EXISTS karmakind;
USE karmakind;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100),
  karma_value INT DEFAULT 0,
  priority INT DEFAULT 0,
  is_completed TINYINT(1) DEFAULT 0,
  task_type VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS habits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  task_id INT NOT NULL,
  streak INT DEFAULT 0,
  last_completed DATE,
  FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);
